{% set name = "napari-imsmicrolink" %}
{% set version = "0.1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-imsmicrolink-{{ version }}.tar.gz
  sha256: 399019eeef7978023b969639d191704f4c15714dcf8945950b772679ed83223b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - aicsimageio
    - bioformats_jar
    - czifile
    - dask-core
    - h5py
    - imagecodecs
    - lxml
    - napari
    - napari-plugin-engine
    - numpy
    - ome-types
    - opencv
    - pandas
    - pint
    - python >=3.7
    - qtpy
    - simpleitk
    - superqt
    - tifffile
    - zarr >=2.10.3

test:
  imports:
    - napari_imsmicrolink
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/napari-imsmicrolink/
  summary: Plugin to perform IMS to microscopy registration using laser ablation marks.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/nhpatterson/napari-imsmicrolink

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - nhpatterson
