{% set name = "napari-imsmicrolink" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-imsmicrolink-{{ version }}.tar.gz
  sha256: cf079e3608be65946f470502b43e4095413f6744d41a0366c31c09283182a6c6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - aicsimageio
    - bioformats_jar
    - czifile
    - dask-core
    - h5py
    - imagecodecs
    - napari
    - napari-plugin-engine
    - numpy
    - opencv
    - pandas
    - python >=3.7
    - qtpy
    - simpleitk
    - tifffile
    - zarr >=2.10.3

test:
  imports:
    - napari_imsmicrolink
  commands:
    - pip list
    # - pip check
  requires:
    - pip

about:
  home: https://github.com/nhpatterson/napari-imsmicrolink
  summary: Plugin to perform IMS to microscopy registration using laser ablation marks.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/napari
    - nhpatterson
